# Generated by Django 6.1.1 on 2026-09-29 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chamasetting',
            name='financial_year_end',
        ),
        migrations.AddField(
            model_name='chamasetting',
            name='absentee_fine',
            field=models.DecimalField(decimal_places=2, default=200.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='chamasetting',
            name='chama_name',
            field=models.CharField(default='My Chama', max_length=200),
        ),
        migrations.AddField(
            model_name='chamasetting',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='chamasetting',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='chamasetting',
            name='email_host',
            field=models.CharField(blank=True, help_text='e.g., smtp.gmail.com', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chamasetting',
            name='email_host_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chamasetting',
            name='email_host_user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chamasetting',
            name='late_fine',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='chamasetting',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='chama_logos/'),
        ),
        migrations.AddField(
            model_name='chamasetting',
            name='non_payment_fine',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='chamasetting',
            name='notify_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chamasetting',
            name='notify_sms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chamasetting',
            name='notify_whatsapp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chamasetting',
            name='sms_api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chamasetting',
            name='sms_provider',
            field=models.CharField(blank=True, choices=[('Africas Talking', 'Africas Talking'), ('Twilio', 'Twilio')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='chamasetting',
            name='sms_sender_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='chamasetting',
            name='whatsapp_api_key',
            field=models.CharField(blank=True, help_text='Meta Cloud API Key', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chamasetting',
            name='whatsapp_phone_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
