# Generated by Django 6.1.1 on 2026-09-29 20:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanguarantor',
            old_name='is_active',
            new_name='is_signed',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='collateral_asset',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='recommended_amount',
        ),
        migrations.AddField(
            model_name='loan',
            name='chairperson_signature',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='repayment_frequency',
            field=models.CharField(choices=[('One Time', 'One Time'), ('Weekly', 'Weekly'), ('Bi-Weekly', 'Bi-Weekly'), ('Monthly', 'Monthly')], default='Monthly', max_length=20),
        ),
        migrations.AddField(
            model_name='loan',
            name='secretary_signature',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='treasurer_signature',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanguarantor',
            name='date_signed',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='LoanSecurity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('serial_number', models.CharField(blank=True, max_length=255, null=True)),
                ('estimated_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('condition', models.CharField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor')], default='Good', max_length=20)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='securities', to='loans.loan')),
            ],
        ),
    ]
